/*
 * ============================================================================
 * TRADINGBOT SCHEMA v1.0
 * Agentic AI Trading Platform
 * ============================================================================
 */

-- ============================================================================
-- SECTION 1: ENUM TYPES
-- ============================================================================

CREATE TYPE public.strategy_mode AS ENUM ('paper', 'live', 'disabled');
CREATE TYPE public.setup_type AS ENUM ('LONG', 'SHORT', 'NONE');
CREATE TYPE public.intent_status AS ENUM ('pending', 'approved', 'rejected', 'executed', 'cancelled', 'expired');
CREATE TYPE public.order_status AS ENUM ('pending', 'submitted', 'accepted', 'filled', 'partially_filled', 'cancelled', 'rejected', 'expired');
CREATE TYPE public.order_type AS ENUM ('market', 'limit', 'stop_limit');
CREATE TYPE public.order_side AS ENUM ('buy', 'sell');
CREATE TYPE public.time_in_force AS ENUM ('gtc', 'ioc', 'day', 'fok');
CREATE TYPE public.risk_severity AS ENUM ('info', 'warning', 'critical', 'fatal');
CREATE TYPE public.whale_status AS ENUM ('active', 'inactive', 'archived');
CREATE TYPE public.strategy_state AS ENUM ('IDLE', 'SETUP', 'TRIGGERED', 'ORDERING', 'IN_POSITION', 'EXITING', 'COOLDOWN');

-- ============================================================================
-- SECTION 2: STRATEGIES
-- ============================================================================

CREATE TABLE public.strategies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  enabled BOOLEAN NOT NULL DEFAULT false,
  mode strategy_mode NOT NULL DEFAULT 'paper',
  symbol VARCHAR(20) NOT NULL DEFAULT 'BTC/USD',
  current_state strategy_state NOT NULL DEFAULT 'IDLE',
  state_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, name)
);

COMMENT ON TABLE public.strategies IS 'Trading strategies configuration';

-- ============================================================================
-- SECTION 3: STRATEGY VERSIONS
-- ============================================================================

CREATE TABLE public.strategy_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  strategy_id UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT false,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  UNIQUE(strategy_id, version)
);

COMMENT ON TABLE public.strategy_versions IS 'Strategy configuration versions history';
COMMENT ON COLUMN public.strategy_versions.config_json IS 'JSON config with entry, exit, execution, risk settings';

-- ============================================================================
-- SECTION 4: SIGNALS
-- ============================================================================

CREATE TABLE public.signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  strategy_id UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  setup setup_type NOT NULL,
  scores_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  confirmations_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  levels_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  raw_data_ref TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_signals_strategy_ts ON public.signals(strategy_id, ts DESC);

COMMENT ON TABLE public.signals IS 'Trading signals generated by the feature engine';

-- ============================================================================
-- SECTION 5: TRADE INTENTS
-- ============================================================================

CREATE TABLE public.trade_intents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  strategy_id UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  signal_id UUID REFERENCES public.signals(id),
  side order_side NOT NULL,
  qty_usd DECIMAL(18, 2) NOT NULL,
  intended_price DECIMAL(18, 8),
  status intent_status NOT NULL DEFAULT 'pending',
  risk_decision JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  executed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  idempotency_key VARCHAR(100) UNIQUE
);

CREATE INDEX idx_intents_strategy ON public.trade_intents(strategy_id, created_at DESC);
CREATE INDEX idx_intents_status ON public.trade_intents(status) WHERE status IN ('pending', 'approved');

COMMENT ON TABLE public.trade_intents IS 'Trade intentions before execution, validated by risk engine';

-- ============================================================================
-- SECTION 6: ORDERS
-- ============================================================================

CREATE TABLE public.orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  intent_id UUID NOT NULL REFERENCES public.trade_intents(id),
  strategy_id UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  alpaca_order_id VARCHAR(100) UNIQUE,
  client_order_id VARCHAR(100) UNIQUE NOT NULL,
  symbol VARCHAR(20) NOT NULL DEFAULT 'BTC/USD',
  side order_side NOT NULL,
  order_type order_type NOT NULL,
  qty DECIMAL(18, 8) NOT NULL,
  limit_price DECIMAL(18, 8),
  stop_price DECIMAL(18, 8),
  time_in_force time_in_force NOT NULL DEFAULT 'gtc',
  status order_status NOT NULL DEFAULT 'pending',
  filled_qty DECIMAL(18, 8) DEFAULT 0,
  filled_avg_price DECIMAL(18, 8),
  is_paper BOOLEAN NOT NULL DEFAULT true,
  raw_request JSONB,
  raw_response JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  submitted_at TIMESTAMPTZ,
  filled_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_strategy ON public.orders(strategy_id, created_at DESC);
CREATE INDEX idx_orders_status ON public.orders(status) WHERE status NOT IN ('filled', 'cancelled', 'rejected');
CREATE INDEX idx_orders_intent_status ON public.orders(intent_id, status);

COMMENT ON TABLE public.orders IS 'Orders sent to Alpaca trading API';

-- ============================================================================
-- SECTION 7: FILLS
-- ============================================================================

CREATE TABLE public.fills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  alpaca_fill_id VARCHAR(100) UNIQUE,
  price DECIMAL(18, 8) NOT NULL,
  qty DECIMAL(18, 8) NOT NULL,
  notional DECIMAL(18, 2) NOT NULL,
  fee DECIMAL(18, 8) DEFAULT 0,
  filled_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  raw_data JSONB
);

CREATE INDEX idx_fills_order ON public.fills(order_id);

COMMENT ON TABLE public.fills IS 'Order execution fills from Alpaca';

-- ============================================================================
-- SECTION 8: POSITIONS
-- ============================================================================

CREATE TABLE public.positions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  strategy_id UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  symbol VARCHAR(20) NOT NULL DEFAULT 'BTC/USD',
  side order_side,
  qty DECIMAL(18, 8) NOT NULL DEFAULT 0,
  avg_entry_price DECIMAL(18, 8),
  current_price DECIMAL(18, 8),
  unrealized_pnl DECIMAL(18, 2) DEFAULT 0,
  realized_pnl DECIMAL(18, 2) DEFAULT 0,
  entry_intent_id UUID REFERENCES public.trade_intents(id),
  entry_order_id UUID REFERENCES public.orders(id),
  entry_at TIMESTAMPTZ,
  stop_loss_price DECIMAL(18, 8),
  take_profit_price DECIMAL(18, 8),
  is_open BOOLEAN NOT NULL DEFAULT false,
  closed_at TIMESTAMPTZ,
  close_reason VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(strategy_id, symbol)
);

CREATE INDEX idx_positions_open ON public.positions(strategy_id) WHERE is_open = true;
CREATE INDEX idx_positions_user_open ON public.positions(user_id, is_open) WHERE is_open = true;

COMMENT ON TABLE public.positions IS 'Current and historical positions';

-- ============================================================================
-- SECTION 9: RISK EVENTS
-- ============================================================================

CREATE TABLE public.risk_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  strategy_id UUID REFERENCES public.strategies(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id),
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  severity risk_severity NOT NULL,
  code VARCHAR(50) NOT NULL,
  message TEXT,
  details_json JSONB,
  action_taken VARCHAR(50),
  acknowledged BOOLEAN DEFAULT false,
  acknowledged_at TIMESTAMPTZ,
  acknowledged_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_risk_events_strategy ON public.risk_events(strategy_id, ts DESC);
CREATE INDEX idx_risk_events_severity ON public.risk_events(severity, ts DESC) WHERE severity IN ('critical', 'fatal');
CREATE INDEX idx_risk_events_unacked ON public.risk_events(user_id, acknowledged) WHERE acknowledged = false;

COMMENT ON TABLE public.risk_events IS 'Risk events and bumper violations';

-- ============================================================================
-- SECTION 10: RISK BUMPERS STATE
-- ============================================================================

CREATE TABLE public.risk_bumpers_state (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID REFERENCES public.strategies(id) ON DELETE CASCADE,
  trading_day DATE NOT NULL DEFAULT CURRENT_DATE,
  daily_loss_usd DECIMAL(18, 2) NOT NULL DEFAULT 0,
  daily_trades_count INTEGER NOT NULL DEFAULT 0,
  cooldown_until TIMESTAMPTZ,
  cooldown_reason VARCHAR(50),
  kill_switch_active BOOLEAN NOT NULL DEFAULT false,
  kill_switch_reason VARCHAR(100),
  kill_switch_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, strategy_id, trading_day)
);

COMMENT ON TABLE public.risk_bumpers_state IS 'Current state of risk bumpers per user/strategy';

-- ============================================================================
-- SECTION 11: WHALE WATCHLIST
-- ============================================================================

CREATE TABLE public.whale_watchlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  address VARCHAR(100) NOT NULL,
  label VARCHAR(100),
  source VARCHAR(50) NOT NULL DEFAULT 'manual',
  score DECIMAL(5, 2) DEFAULT 0,
  rank INTEGER,
  status whale_status NOT NULL DEFAULT 'active',
  notes TEXT,
  tags VARCHAR(50)[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_activity_at TIMESTAMPTZ,
  UNIQUE(user_id, address)
);

CREATE INDEX idx_whale_watchlist_user ON public.whale_watchlist(user_id, status);

COMMENT ON TABLE public.whale_watchlist IS 'Whale wallet addresses to monitor';

-- ============================================================================
-- SECTION 12: WHALE SNAPSHOTS
-- ============================================================================

CREATE TABLE public.whale_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  whale_id UUID NOT NULL REFERENCES public.whale_watchlist(id) ON DELETE CASCADE,
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  state_json JSONB NOT NULL,
  delta_json JSONB,
  is_significant BOOLEAN DEFAULT false,
  significance_reason VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_whale_snapshots_whale ON public.whale_snapshots(whale_id, ts DESC);
CREATE INDEX idx_whale_snapshots_significant ON public.whale_snapshots(ts DESC) WHERE is_significant = true;

COMMENT ON TABLE public.whale_snapshots IS 'Historical snapshots of whale positions';

-- ============================================================================
-- SECTION 13: WHALE EVENTS
-- ============================================================================

CREATE TABLE public.whale_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  whale_id UUID NOT NULL REFERENCES public.whale_watchlist(id) ON DELETE CASCADE,
  snapshot_id UUID REFERENCES public.whale_snapshots(id),
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_type VARCHAR(50) NOT NULL,
  symbol VARCHAR(20),
  direction VARCHAR(10),
  details_json JSONB,
  used_as_confirmation BOOLEAN DEFAULT false,
  used_in_signal_id UUID REFERENCES public.signals(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_whale_events_ts ON public.whale_events(ts DESC);

COMMENT ON TABLE public.whale_events IS 'Significant whale trading events';

-- ============================================================================
-- SECTION 14: AGENT TRACES
-- ============================================================================

CREATE TABLE public.agent_traces (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID REFERENCES public.strategies(id) ON DELETE CASCADE,
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  agent_name VARCHAR(50) NOT NULL,
  intent_id UUID REFERENCES public.trade_intents(id),
  signal_id UUID REFERENCES public.signals(id),
  input_summary TEXT,
  input_ref TEXT,
  output_json JSONB NOT NULL,
  eval_score DECIMAL(3, 2),
  eval_feedback TEXT,
  tokens_input INTEGER,
  tokens_output INTEGER,
  cost_usd DECIMAL(10, 6),
  latency_ms INTEGER,
  model_used VARCHAR(50),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_agent_traces_user ON public.agent_traces(user_id, ts DESC);
CREATE INDEX idx_agent_traces_agent ON public.agent_traces(agent_name, ts DESC);
CREATE INDEX idx_agent_traces_output_gin ON public.agent_traces USING gin(output_json);

COMMENT ON TABLE public.agent_traces IS 'OpenAI agent execution traces';

-- ============================================================================
-- SECTION 15: AGENT PROPOSALS
-- ============================================================================

CREATE TABLE public.agent_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID NOT NULL REFERENCES public.strategies(id) ON DELETE CASCADE,
  agent_trace_id UUID REFERENCES public.agent_traces(id),
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  proposal_type VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT,
  current_config JSONB,
  proposed_config JSONB,
  diff_summary TEXT,
  rationale TEXT,
  expected_impact TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES auth.users(id),
  review_notes TEXT,
  applied_at TIMESTAMPTZ,
  applied_version_id UUID REFERENCES public.strategy_versions(id),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_proposals_pending ON public.agent_proposals(user_id, status) WHERE status = 'pending';
CREATE INDEX idx_proposals_user_pending ON public.agent_proposals(user_id, status) WHERE status = 'pending';

COMMENT ON TABLE public.agent_proposals IS 'AI agent proposals for strategy changes';

-- ============================================================================
-- SECTION 16: MARKET DATA CACHE
-- ============================================================================

CREATE TABLE public.market_data_cache (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol VARCHAR(20) NOT NULL,
  data_type VARCHAR(30) NOT NULL,
  ts TIMESTAMPTZ NOT NULL,
  data_json JSONB NOT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'hyperliquid',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ
);

CREATE INDEX idx_market_data_symbol_ts ON public.market_data_cache(symbol, data_type, ts DESC);

COMMENT ON TABLE public.market_data_cache IS 'Cached market data from Hyperliquid';

-- ============================================================================
-- SECTION 17: DAILY METRICS
-- ============================================================================

CREATE TABLE public.daily_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id UUID REFERENCES public.strategies(id) ON DELETE CASCADE,
  trading_day DATE NOT NULL,
  total_trades INTEGER NOT NULL DEFAULT 0,
  winning_trades INTEGER NOT NULL DEFAULT 0,
  losing_trades INTEGER NOT NULL DEFAULT 0,
  gross_pnl DECIMAL(18, 2) NOT NULL DEFAULT 0,
  fees_paid DECIMAL(18, 2) NOT NULL DEFAULT 0,
  net_pnl DECIMAL(18, 2) NOT NULL DEFAULT 0,
  max_drawdown DECIMAL(18, 2) DEFAULT 0,
  max_position_size DECIMAL(18, 2) DEFAULT 0,
  signals_generated INTEGER DEFAULT 0,
  signals_executed INTEGER DEFAULT 0,
  signals_rejected INTEGER DEFAULT 0,
  win_rate DECIMAL(5, 2),
  avg_win DECIMAL(18, 2),
  avg_loss DECIMAL(18, 2),
  profit_factor DECIMAL(8, 2),
  sharpe_ratio DECIMAL(8, 4),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, strategy_id, trading_day)
);

CREATE INDEX idx_daily_metrics_user ON public.daily_metrics(user_id, trading_day DESC);

COMMENT ON TABLE public.daily_metrics IS 'Aggregated daily trading metrics';

-- ============================================================================
-- SECTION 18: SYSTEM CONFIG
-- ============================================================================

CREATE TABLE public.system_config (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  alpaca_paper_enabled BOOLEAN NOT NULL DEFAULT true,
  alpaca_live_enabled BOOLEAN NOT NULL DEFAULT false,
  enable_whale_tracking BOOLEAN NOT NULL DEFAULT true,
  enable_agent_explanations BOOLEAN NOT NULL DEFAULT true,
  enable_agent_proposals BOOLEAN NOT NULL DEFAULT false,
  notify_on_trade BOOLEAN NOT NULL DEFAULT true,
  notify_on_risk_event BOOLEAN NOT NULL DEFAULT true,
  notify_on_proposal BOOLEAN NOT NULL DEFAULT true,
  notification_channels JSONB DEFAULT '{"email": true, "push": false}'::jsonb,
  alpaca_key_ref VARCHAR(100),
  openai_key_ref VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id)
);

COMMENT ON TABLE public.system_config IS 'User-level system configuration';

-- ============================================================================
-- SECTION 19: API KEYS
-- ============================================================================

CREATE TABLE public.api_keys (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider VARCHAR(30) NOT NULL,
  key_name VARCHAR(100),
  api_key_encrypted TEXT NOT NULL,
  api_secret_encrypted TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  is_valid BOOLEAN,
  last_validated_at TIMESTAMPTZ,
  validation_error TEXT,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, provider)
);

COMMENT ON TABLE public.api_keys IS 'Encrypted API keys for external services';

-- ============================================================================
-- SECTION 20: AUDIT LOG
-- ============================================================================

CREATE TABLE public.audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id),
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  action VARCHAR(50) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id UUID,
  old_value JSONB,
  new_value JSONB,
  ip_address INET,
  user_agent TEXT,
  source VARCHAR(30) NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_user ON public.audit_log(user_id, ts DESC);
CREATE INDEX idx_audit_log_entity ON public.audit_log(entity_type, entity_id, ts DESC);

COMMENT ON TABLE public.audit_log IS 'Complete audit trail of all actions';
